# Generated by Django 5.1.3 on 2024-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("text", models.TextField(verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blogs/photo",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateField(verbose_name="Дата создания")),
                (
                    "is_publicated",
                    models.BooleanField(verbose_name="Признак публикации"),
                ),
                ("views", models.IntegerField(verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
    ]
